# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  projectdesignwebsite:
    image: projectdesignwebsite
    build:
      context: .
      dockerfile: src/WebSite/Dockerfile
    ports:
      - 80:80
